// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AttachmentKind } from "./AttachmentKind";

/**
 * 附件引用占位（FL-03 F-03-12 / FL-09 引用句柄语义）。M2 Sprint 不消费。
 */
export type AttachmentRef = { attachmentId: string, kind: AttachmentKind, 
/**
 * 对象存储引用句柄（不可枚举，§3）。
 */
handle: string, };
