// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 语音上行元数据，随 multipart 一起提交给网关。
 */
export type AudioMeta = { durationMs: number, 
/**
 * 编码格式标识，取值必须等于 `DEFAULT_AUDIO_FORMAT`。
 */
format: string, sampleRateHz: number, channels: number, };
