// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 采集模式（§2.2 C4 双模式）。M2 Sprint 先落 push-to-talk（M2-03），
 * 常驻 VAD 归 M2-06。
 */
export type CaptureMode = "push_to_talk" | "continuous_vad";
