// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CaptureFailed = { 
/**
 * 面向排障的原因码（如 permission_denied / device_busy / too_long）。
 */
reason: string, };
