// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AttachmentRef } from "./AttachmentRef";
import type { ChatRole } from "./ChatRole";
import type { MessageSource } from "./MessageSource";

/**
 * 一条对话消息。用户与助手消息同构，靠 `role` 区分。
 */
export type ChatMessage = { messageId: string, sessionId: string, 
/**
 * 同一轮问答（用户消息 + 助手回复）共享 turn_id。
 */
turnId: string, role: ChatRole, source: MessageSource, content: string, 
/**
 * Unix epoch 毫秒。
 */
ts: number, 
/**
 * 这条助手回复是被**打断**的半句（施工单 M33-01，F-08-08）。
 *
 * 取消的语义是"停止推进"而不是"抹掉"：AC-08-6 明写「已产生内容不丢失」，
 * 用户已经听见/看见的那半句必须留在历史里，只是要标出来——
 * 不标的话它读起来像是助手好端端地把话说了一半。
 *
 * `Option` 而不是 `bool`：老数据与老端上都没有这个字段，
 * 缺省（`None`）与 `Some(false)` 一样都表示"正常收口"。
 */
cancelled?: boolean | null, 
/**
 * 这条**用户**消息随轮带上的附件（施工单 M80-01，F-03-08 / F-09-09）。
 *
 * 只有引用，没有字节：端上拿 `handle` 经 Rust 侧 `GET /v1/attachments/:handle` 取原件
 * （WebView 里没有令牌，`<img src>` 加不了 Authorization 头）。
 * 助手消息恒无此字段；老数据与老端上没有这个字段，缺省与空数组同义。
 */
attachments?: Array<AttachmentRef> | null, };
