// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClientDetection } from "./ClientDetection";

/**
 * 一张照片的端上检测结果（ACR-046），随 `/messages` 体的 `detections`（按附件句柄索引）上行。
 *
 * `items` 为空也要发：端上跑过、没框到，服务端据此说「未识别到指示灯」并给补拍提示，
 * **不回落云端定位**（ACR-044 产品决定）。检测没跑完的照片不带——服务端自己框。
 */
export type ClientDetections = { 
/**
 * 转正后的像素尺寸（只作留痕与自检，框已归一化）。
 */
width: number, height: number, items: Array<ClientDetection>, 
/**
 * 端上推理耗时（毫秒），进服务端 trace。
 */
inferMs?: number | null, };
