// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionEvent } from "./SessionEvent";

/**
 * SSE 事件封套：每条下行事件的统一外壳。
 *
 * `event_id` 单调递增（会话内），支撑 `Last-Event-ID` 断点续传（§3）。
 * `session_id` 贯穿全链路（§3），任何事件不得缺失。
 */
export type EventEnvelope = { eventId: string, sessionId: string, 
/**
 * Unix epoch 毫秒。
 */
ts: number, event: SessionEvent, };
