// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatMessage } from "./ChatMessage";

export type HistoryPage = { 
/**
 * 按时间正序排列。
 */
messages: Array<ChatMessage>, hasMore: boolean, 
/**
 * 继续向前翻页的游标；无更多时为 null。
 */
nextBefore: string | null, };
