// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PermissionDetail } from "./PermissionDetail";

/**
 * HITL 权限确认请求（FL-04 F-04-12：动作类型、明细项、影响范围、中断点 id）。
 *
 * M2 Sprint 不下发此事件；类型对齐 §8.4 的"需确认"档裁决。
 */
export type PermissionRequest = { 
/**
 * 中断点 id，resume 时回传关联。
 */
interruptId: string, 
/**
 * 动作类别（如 calendar_write / appointment）。
 */
action: string, 
/**
 * 弹窗标题级别的动作说明。
 */
title: string, 
/**
 * 将要执行的具体明细 —— 不允许只显示动作名称（FL-04 AC-04-2）。
 */
details: Array<PermissionDetail>, 
/**
 * 影响范围（如写入哪个日历账号）。
 */
scope: string | null, 
/**
 * 将提供给第三方的**个人信息项**（F-26-09 / AC-15-7）。
 *
 * # 为什么不塞进 `details`
 *
 * 混在一起，用户不会意识到这几行的性质和"门店地址"完全不同——
 * 一个是"这次动作是什么"，一个是"我的哪些信息要发出去"。
 * 端上必须把它渲染成独立一块，所以协议上也必须是独立一段。
 *
 * 空数组 = 本次动作不外发任何个人信息，与"没有这个字段"语义相同
 * （`serde(default)` 让旧版本事件仍可反序列化）。
 * 值在生成侧已掩码（`enterprise/backend/shared/tools` 的 `describeDisclosure`），
 * **端上只渲染、不自己拼**：两处各拼一份时，用户看到的和实际发出去的会对不上。
 */
disclosure: Array<PermissionDetail>, };
