// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MessageSource } from "./MessageSource";

export type PromptAccepted = { turnId: string, source: MessageSource, 
/**
 * 语音输入的 ASR 识别原文；文本输入为 null。
 */
transcript: string | null, };
