// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UpdateBranch } from "./UpdateBranch";
import type { UpdateDelta } from "./UpdateDelta";
import type { UpdateFiller } from "./UpdateFiller";
import type { UpdateRetract } from "./UpdateRetract";
import type { UpdateState } from "./UpdateState";
import type { UpdateTitle } from "./UpdateTitle";
import type { UpdateTurnEnd } from "./UpdateTurnEnd";

/**
 * `update` 事件的六种载荷。序列化形如
 * `{"type":"update","kind":"delta","turnId":"…","text":"…"}`。
 *
 * 加新变体时 `carlife-core::fanout::project` 的 match 会编译失败——
 * 那是刻意的：**新事件类型必须被显式处置**，忽略也要写出来并说明理由。
 */
export type SessionUpdate = { "kind": "delta" } & UpdateDelta | { "kind": "state" } & UpdateState | { "kind": "turn_end" } & UpdateTurnEnd | { "kind": "branch" } & UpdateBranch | { "kind": "retract" } & UpdateRetract | { "kind": "filler" } & UpdateFiller | { "kind": "title" } & UpdateTitle;
