// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PermissionRequest } from "./PermissionRequest";
import type { PromptAccepted } from "./PromptAccepted";
import type { SessionOpened } from "./SessionOpened";
import type { SessionUpdate } from "./SessionUpdate";
import type { ToolCallEvent } from "./ToolCallEvent";

/**
 * 五类会话事件（ACP 语义投影，§3）。
 */
export type SessionEvent = { "type": "session" } & SessionOpened | { "type": "prompt" } & PromptAccepted | { "type": "update" } & SessionUpdate | { "type": "permission" } & PermissionRequest | { "type": "tool_call" } & ToolCallEvent;
