// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 为什么会变。端上不按它分支，只用来记日志与排障。
 */
export type SessionsChangedReason = "connected" | "message" | "title" | "closed";
