// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateRetract = { turnId: string, 
/**
 * 替换文本。**必填**——撤回后屏幕不能是空的，
 * 用户会以为应用坏了而不是"这条被拦了"。
 */
replacement: string, 
/**
 * 撤回原因，给端上展示用的一句话。
 *
 * **不带命中的具体标签**：那是审计里的东西，摆给用户看等于告诉他
 * 换个说法就能绕过去。
 */
reason: string, };
