// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserEvent } from "./UserEvent";

/**
 * 账号级事件封套。
 */
export type UserEventEnvelope = { 
/**
 * Unix epoch 毫秒。
 */
ts: number, event: UserEvent, };
