// @carlife/tools —— 工具实现（经 enterprise/backend/pi-agents/.pi/extensions 的 pi.registerTool 注入 pi）
//
// 边界：本包**不 import enterprise/backend/ 下的服务**（AC-34-4：工具必须可脱离 Agent 与 LLM 单测），
// 由 `check:arch` 的 boundary 检查守住。

export {
  defineExternalTool,
  ToolError,
  type ExternalTool,
  type ExternalToolSpec,
  type ToolCallContext,
  type ToolMode,
  type ToolResult,
  type ToolSource,
} from "./external";

export {
  TOOL_REGISTRY,
  describeForPi,
  getTool,
  getToolObserver,
  getToolStartObserver,
  invokeTool,
  listExposableForMcp,
  listForAgent,
  setToolObserver,
  setToolStartObserver,
  type AgentName,
  type PiToolDescriptor,
  type ToolInvocationObservation,
  type ToolObserver,
  type ToolStartObserver,
  type ToolStartNotice,
  type ToolRegistration,
} from "./registry";

export {
  calendarTool,
  createCalendarTool,
  createMockBackend,
  createFanoutCalendarBackend,
  setCalendarBackend,
  getCalendarBackend,
  type BusySlot,
  type CalendarArgs,
  type CalendarBackend,
  type CalendarBinding,
  type CalendarEventDraft,
  type CalendarResult,
} from "./calendar";
export { createGoogleCalendarBackend, googleEventId, type GoogleCalendarConfig } from "./calendar-google";
export { createCaldavBackend, buildIcs, caldavUid, type CaldavConfig } from "./calendar-caldav";
export {
  setEnvCache,
  createRedisEnvCache,
  getEnvCacheStats,
  resetEnvCacheStats,
  envCacheKey,
  roundCoord,
  withEnvCache,
  ENV_TTL,
  listEnvCache,
  getEnvCacheEntry,
  regeoPointsForAdcode,
  regeoKeyToPoint,
  namespaceOf,
  paginateKeys,
  PREVIEW_CHARS,
  SCAN_CAP,
  REGEO_LOOKUP_CAP,
  type EnvCacheBackend,
  type EnvCacheEntry,
  type EnvCacheDetail,
  type RegeoPoint,
  type EnvCacheListing,
  type EnvCacheListOptions,
  type CacheStats,
} from "./env-cache";
export { describeEnvCacheEntry, type EnvCacheDescription } from "./env-cache-summary";
export {
  cabinApplyPreferencesTool,
  setCabinApplyDeps,
  type CabinApplyPreferencesArgs,
  type CabinApplyPreferencesData,
  type CabinTranslator,
} from "./cabin-apply";
export {
  describePreference,
  memberPreferenceSetTool,
  setPreferenceMemberStore,
  type MemberPreferenceSetArgs,
  type MemberPreferenceSetData,
} from "./member-preference";
export {
  cabinStatusTool,
  resolveCabinVin,
  type CabinStatusToolData,
  type CabinVinArgs,
} from "./cabin-status";
export {
  CABIN_COMFORT_DOMAINS,
  cabinChildModeTool,
  cabinControlTool,
  deriveRequestId,
  type CabinControlArgs,
  type CabinControlData,
} from "./cabin-control";
export {
  CABIN_MEDIA_COMMANDS,
  cabinMediaTool,
  type CabinMediaArgs,
  type CabinMediaData,
  type CabinMediaCommandName,
} from "./cabin-media";
export {
  CabinUnboundError,
  CabinVehicleGoneError,
  createCabinClient,
  createHttpCabinBackend,
  getCabinClient,
  requireCabinClient,
  setCabinClient,
  type CabinApplyData,
  type CabinApplyOp,
  type CabinApplyResponse,
  type CabinAudioHealth,
  type CabinBindingStore,
  type CabinCapabilities,
  type CabinChange,
  type CabinClient,
  type CabinMediaCommand,
  type CabinMediaLibrary,
  type CabinMediaResponse,
  type CabinOpResult,
  type CabinPlayerView,
  type CabinSinkBeat,
  type CabinState,
  type CabinStatusData,
  type CabinStatusResponse,
  type CabinTrack,
  type CabinTrackStream,
  type RawCabinBackend,
} from "./cabin-backend";
export { calcCost, costCalcTool, type CostAssumptions, type CostBreakdown, type CostCalcArgs } from "./cost-calc";
export {
  quoteInsurance,
  insuranceQuoteTool,
  INSURANCE_COEFFICIENTS,
  THIRD_PARTY_TIERS,
  USELESS_RANGE_RATIO,
  type InsuranceQuoteArgs,
  type InsuranceQuote,
  type InsuranceItem,
  type ThirdPartyTier,
  type QuotedAssumption,
} from "./insurance-quote";
export {
  calcLoan,
  loanCalcTool,
  equalInstallmentMonthly,
  ASSUMED_RATE_BAND,
  type LoanCalcArgs,
  type LoanBreakdown,
  type Range,
  type RateSource,
} from "./loan-calc";
export {
  trimCompareTool,
  createTrimCompareTool,
  diffRows,
  alignAcrossModels,
  priceFloorOf,
  type TrimCompareArgs,
  type TrimCompareResult,
  type TrimAlignment,
  type TrimRow,
  type TrimPair,
  type TrimDiff,
  type TrimDiffField,
} from "./trim-compare";
export {
  weatherTool,
  type WeatherArgs,
  type WeatherSegment,
  type WeatherObservation,
  type WeatherAlarm,
} from "./weather";

export {
  pretripItemsTool,
  recommendPretripItems,
  fallbackPretripItems,
  reduceSegments,
  allPretripKeysKnown,
  MAX_PRETRIP_ITEMS,
  type PretripItemsArgs,
  type PretripItemsData,
  type PretripItemPick,
  type PretripWeatherView,
} from "./pretrip-items";

export {
  destinationHighlightsTool,
  parseHighlights,
  readWebSearchTurn,
  buildPrompt as buildHighlightsPrompt,
  setDestinationSearch,
  getDestinationSearch,
  MAX_FOODS,
  MAX_SPOTS,
  MAX_PHOTO_TIPS,
  MAX_NOTE_CHARS,
  type DestinationHighlightsArgs,
  type DestinationHighlightsData,
  type DestinationSearchConfig,
  type HighlightEntry,
  type HighlightSource,
  type PhotoTip,
  type SearchResultRef,
  type WebSearchTurn,
} from "./destination-highlights";
export {
  createCmaClient,
  setCmaClient,
  getCmaClient,
  CMA_LIMITS,
  type CmaClient,
  type CmaClientOptions,
  type CmaStation,
  type CmaObservation,
  type CmaDaily,
  type CmaAlarm,
  type CmaView,
} from "./cma";
export {
  createAmapClient,
  setAmapClient,
  getAmapClient,
  type AmapCast,
  type AmapClient,
  type AmapClientOptions,
  type AmapForecast,
  type AmapPlace,
  type AmapPoi,
  type AmapPath,
  type AmapRegeo,
  type LngLat,
} from "./amap";
export {
  mapRouteTool,
  AMAP_STRATEGY,
  ROUTE_STRATEGIES,
  setRestStopCandidateRecorder,
  type MapRouteArgs,
  type MapRouteData,
  type PlaceInput,
  type ResolvedPlace,
  type RestStop,
  type RestStopCandidateRecorder,
  type RouteSamplePoint,
  type RouteStrategy,
  type RouteSummary,
} from "./map-route";
export {
  ragflowTool,
  setRagClient,
  getRagClient,
  type RagflowArgs,
  type RagflowData,
} from "./ragflow";
export {
  submitHotelsTool,
  submitTourDaysTool,
  submitTransitTool,
  submitDriveDraftTool,
  submitNavPlanTool,
  submitGuideSpotsTool,
  submitGuideAccessTool,
  submitGuideComfortTool,
  setBranchSubmissionSink,
  type BranchSubmissionSink,
  type SubmitHotelsArgs,
  type SubmittedHotel,
  type SubmitGuideSpotsArgs,
  type SubmitGuideAccessArgs,
  type SubmitGuideComfortArgs,
  type SubmittedGuideSpot,
  type SubmitNavPlanArgs,
  type SubmittedNavWaypoint,
} from "./branch-submit";
export {
  webSearchTool,
  setWebSearch,
  getWebSearch,
  callAnthropicWebSearch,
  setSearchResultRecorder,
  type WebSearchConfig,
  type WebSearchArgs,
  type WebSearchData,
  type SearchResultRecorder,
  type CallWebSearchOptions,
} from "./web-search";
export {
  preferenceRecallTool,
  setPreferenceStore,
  getPreferenceStore,
  type PreferenceRecallArgs,
  type PreferenceRecallData,
  type PreferenceStore,
  type RecalledPreference,
} from "./memory";
export {
  energyGapTool,
  computeEnergyGap,
  type EnergyGapArgs,
  type EnergyGapData,
  type EnergyUnit,
} from "./energy-gap";
export {
  refuelLogTool,
  setRefuelStore,
  getRefuelStore,
  type RefuelLogArgs,
  type RefuelLogData,
  type RefuelLogStore,
} from "./refuel-log";
export {
  dataFreshnessTool,
  setFreshnessThresholds,
  FRESHNESS_ITEM_LABEL,
  type DataFreshnessArgs,
  type DataFreshnessData,
} from "./data-freshness";
export {
  usageProfileTool,
  setUsageStore,
  getUsageStore,
  type UsageProfileArgs,
  type UsageProfileData,
} from "./usage-profile";
export {
  vehicleMemberTool,
  setMemberStores,
  getMemberStore,
  type VehicleMemberArgs,
  type VehicleMemberData,
  type MemberBrief,
  type MemberListData,
  type MemberProfileData,
  type MemberHistoryData,
} from "./vehicle-member";
// 联系方式读写（M19-06）。`resolveContactSecret` 也导出，但它**不是工具**——
// `test_drive_book` 用它在工具层内部取真号，见 contact.ts 末尾的说明。
export {
  contactLookupTool,
  contactUpdateTool,
  resolveContactSecret,
  type ContactLookupArgs,
  type ContactUpdateArgs,
  type ContactLookupData,
  type ContactUpdateData,
  type ContactBrief,
} from "./contact";
export {
  vehicleProfileTool,
  vehicleProfileWriteTool,
  setVehicleStore,
  getVehicleStore,
  type VehicleReadArgs,
  type VehicleReadData,
  type VehicleWriteArgs,
} from "./vehicle-profile";
export {
  chargingTool,
  createChargingTool,
  createAmapChargingBackend,
  planChargeStops,
  parsePowerKw,
  haversineKm,
  SAFETY_SOC,
  TARGET_SOC,
  QUEUE_NOTICE,
  type ChargingArgs,
  type ChargingResult,
  type ChargingStop,
  type ChargingStation,
  type ChargingBackend,
} from "./charging";
export {
  poiSearchTool,
  createPoiSearchTool,
  PRICE_NOTICE,
  type PoiSearchArgs,
  type PoiSearchResult,
  type PoiCandidate,
  type PoiSearchBackend,
  type PoiCategory,
} from "./poi-search";
export {
  routeAuditTool,
  createRouteAuditTool,
  setRouteAuditStore,
  auditDay,
  auditJourney,
  optimizeOrder,
  findCrossings,
  pathKm,
  ROUTE_AUDIT_NOTICE,
  type RouteAuditArgs,
  type RouteAuditResult,
  type RouteAuditDayResult,
  type JourneyAudit,
  type JourneyDayInput,
  type JourneyRegroupSuggestion,
  type JourneyDayOrderSuggestion,
  type RouteAuditRecordPayload,
  type RouteAuditStore,
  type RouteGeocodeBackend,
  type RoutePoint,
} from "./route-audit";
export {
  transitRouteTool,
  createTransitRouteTool,
  TRANSIT_NOTE,
  type TransitRouteArgs,
  type TransitRouteResult,
  type TrainOption,
  type TransitBackend,
} from "./transit-route";
export {
  carCatalogTool,
  createCarCatalogTool,
  createRagCatalogBackend,
  type CarCatalogArgs,
  type CarCatalogResult,
  type CatalogChunk,
  type CatalogBackend,
  type RagRetrieveLike,
} from "./car-catalog";
export {
  tripPlanCommitTool,
  tripPlanCancelTool,
  tripPlanUpdateTool,
  tripPlanNavTool,
  tripPlanListTool,
  tripPlanQueryTool,
  setTripPlanStore,
  type TripPlanCommitArgs,
  type TripPlanCommitData,
  type TripPlanNavArgs,
  type TripPlanNavData,
  type TripPlanStore,
} from "./trip-plan-commit";
export {
  dealerStoresTool,
  dealerSlotsTool,
  dealerPricingTool,
  testDriveBookTool,
  setDealerBackend,
  getDealerBackend,
  createHttpDealerBackend,
  type DealerBackend,
  type DealerStore,
  type DealerSlot,
  type DealerTrim,
  type DealerBooking,
  type TestDriveContact,
  type TestDriveBookArgs,
} from "./dealer";
export {
  appointmentTool,
  createAppointmentTool,
  createMockAppointmentBackend,
  createDealerAppointmentBackend,
  createRepairAppointmentBackend,
  setAppointmentBackend,
  describeDisclosure,
  maskPhone,
  type AppointmentArgs,
  type AppointmentResult,
  type AppointmentContact,
  type AppointmentKind,
  type AppointmentBackend,
} from "./appointment";
export {
  repairHistoryTool,
  repairQuoteTool,
  repairStationsTool,
  repairSlotsTool,
  setRepairBackend,
  getRepairBackend,
  createHttpRepairBackend,
  type RepairBackend,
  type RepairHistoryRecord,
  type RepairStation,
  type RepairSlot,
  type RepairQuote,
  type RepairQuoteItem,
} from "./repair";
export {
  insurancePolicyTool,
  insurancePrecheckTool,
  setInsuranceBackend,
  getInsuranceBackend,
  createHttpInsuranceBackend,
  type InsuranceBackend,
  type InsurancePolicy,
  type PrecheckResult,
  type PrecheckBreakdownRow,
} from "./insurance-claims";
