// @carlife/tools —— 工具实现（经 enterprise/backend/pi-agents/.pi/extensions 的 pi.registerTool 注入 pi）
//
// 边界：本包**不 import enterprise/backend/ 下的服务**（AC-34-4：工具必须可脱离 Agent 与 LLM 单测），
// 由 `check:arch` 的 boundary 检查守住。

export {
  defineExternalTool,
  ToolError,
  type ExternalTool,
  type ExternalToolSpec,
  type ToolCallContext,
  type ToolMode,
  type ToolResult,
  type ToolSource,
} from "./external";

export {
  TOOL_REGISTRY,
  describeForPi,
  getTool,
  getToolObserver,
  getToolStartObserver,
  invokeTool,
  listExposableForMcp,
  listForAgent,
  setToolObserver,
  setToolStartObserver,
  type AgentName,
  type PiToolDescriptor,
  type ToolInvocationObservation,
  type ToolObserver,
  type ToolStartObserver,
  type ToolStartNotice,
  type ToolRegistration,
} from "./registry";

export { openWaitMeter, recordWait } from "./wait-meter";

export {
  setEnvCache,
  createRedisEnvCache,
  getEnvCacheStats,
  resetEnvCacheStats,
  envCacheKey,
  roundCoord,
  withEnvCache,
  ENV_TTL,
  listEnvCache,
  getEnvCacheEntry,
  regeoPointsForAdcode,
  regeoKeyToPoint,
  namespaceOf,
  paginateKeys,
  PREVIEW_CHARS,
  SCAN_CAP,
  REGEO_LOOKUP_CAP,
  type EnvCacheBackend,
  type EnvCacheEntry,
  type EnvCacheDetail,
  type RegeoPoint,
  type EnvCacheListing,
  type EnvCacheListOptions,
  type CacheStats,
} from "./env-cache";
export { describeEnvCacheEntry, type EnvCacheDescription } from "./env-cache-summary";
export {
  cabinApplyPreferencesTool,
  setCabinApplyDeps,
  type CabinApplyPreferencesArgs,
  type CabinApplyPreferencesData,
  type CabinTranslator,
} from "./cabin-apply";
export {
  describePreference,
  memberPreferenceSetTool,
  setPreferenceMemberStore,
  type MemberPreferenceSetArgs,
  type MemberPreferenceSetData,
} from "./member-preference";
export {
  cabinStatusTool,
  resolveCabinVin,
  type CabinStatusToolData,
  type CabinVinArgs,
} from "./cabin-status";
export {
  deriveFullRangeKm,
  vehicleEnergyTool,
  type VehicleEnergyData,
} from "./vehicle-energy";
export {
  CABIN_COMFORT_DOMAINS,
  cabinChildModeTool,
  cabinControlTool,
  deriveRequestId,
  type CabinControlArgs,
  type CabinControlData,
} from "./cabin-control";
export {
  CABIN_MEDIA_COMMANDS,
  cabinMediaTool,
  type CabinMediaArgs,
  type CabinMediaData,
  type CabinMediaCommandName,
} from "./cabin-media";
export {
  CabinUnboundError,
  CabinVehicleGoneError,
  createCabinClient,
  createHttpCabinBackend,
  getCabinClient,
  requireCabinClient,
  setCabinClient,
  type CabinApplyData,
  type CabinApplyOp,
  type CabinApplyResponse,
  type CabinAudioHealth,
  type CabinBindingStore,
  type CabinCapabilities,
  type CabinChange,
  type CabinClient,
  type CabinMediaCommand,
  type CabinMediaLibrary,
  type CabinMediaResponse,
  type CabinOpResult,
  type CabinPlayerView,
  type CabinSinkBeat,
  type CabinState,
  type CabinStatusData,
  type CabinStatusResponse,
  type CabinTrack,
  type CabinTrackStream,
  type RawCabinBackend,
} from "./cabin-backend";
export { calcCost, costCalcTool, type CostAssumptions, type CostBreakdown, type CostCalcArgs } from "./cost-calc";
export {
  quoteInsurance,
  insuranceQuoteTool,
  INSURANCE_COEFFICIENTS,
  THIRD_PARTY_TIERS,
  USELESS_RANGE_RATIO,
  type InsuranceQuoteArgs,
  type InsuranceQuote,
  type InsuranceItem,
  type ThirdPartyTier,
  type QuotedAssumption,
} from "./insurance-quote";
export {
  calcLoan,
  loanCalcTool,
  equalInstallmentMonthly,
  ASSUMED_RATE_BAND,
  type LoanCalcArgs,
  type LoanBreakdown,
  type Range,
  type RateSource,
} from "./loan-calc";
export {
  trimCompareTool,
  createTrimCompareTool,
  diffRows,
  alignAcrossModels,
  priceFloorOf,
  type TrimCompareArgs,
  type TrimCompareResult,
  type TrimAlignment,
  type TrimRow,
  type TrimPair,
  type TrimDiff,
  type TrimDiffField,
} from "./trim-compare";
export {
  weatherTool,
  type WeatherArgs,
  type WeatherSegment,
  type WeatherObservation,
  type WeatherAlarm,
} from "./weather";

export {
  pretripItemsTool,
  recommendPretripItems,
  fallbackPretripItems,
  reduceSegments,
  classifyWeatherKind,
  allPretripKeysKnown,
  MAX_PRETRIP_ITEMS,
  type PretripItemsArgs,
  type PretripItemsData,
  type PretripItemPick,
  type PretripWeatherView,
} from "./pretrip-items";

export {
  destinationHighlightsTool,
  parseHighlights,
  readWebSearchTurn,
  buildPrompt as buildHighlightsPrompt,
  setDestinationSearch,
  getDestinationSearch,
  MAX_FOODS,
  MAX_SPOTS,
  MAX_PHOTO_TIPS,
  MAX_NOTE_CHARS,
  type DestinationHighlightsArgs,
  type DestinationHighlightsData,
  type DestinationSearchConfig,
  type HighlightEntry,
  type HighlightSource,
  type PhotoTip,
  type SearchResultRef,
  type WebSearchTurn,
} from "./destination-highlights";
export {
  createCmaClient,
  setCmaClient,
  getCmaClient,
  CMA_LIMITS,
  type CmaClient,
  type CmaClientOptions,
  type CmaStation,
  type CmaObservation,
  type CmaDaily,
  type CmaAlarm,
  type CmaView,
} from "./cma";
export {
  createAmapClient,
  setAmapClient,
  AMAP_KEY_ENV_NAMES,
  AMAP_KEY_MAX,
  // key 池：三处读法收成一个（M100-01）；台账与预算见 ./amap-ledger。
  resolveAmapKeys,
  AMAP_DEFAULT_DAILY_BUDGET,
  AMAP_SOFT_CEILING,
  amapBudgetFromEnv,
  AMAP_REVIVE_PROBE_MS,
  type AmapKeySource,
  type AmapLanePreference,
  getAmapClient,
  // 「被限流」必须能和「高德说没有这个地方」分开——判据在这里，别在调用点扒 message。
  isRateLimited,
  // 「这把 key 今天用光了」与限流是两回事：换 key，不重试。
  isDailyQuotaExhausted,
  AMAP_ALL_LANES_RETIRED_CODE,
  splitLegMinutes,
  AMAP_WAYPOINT_MARK,
  AMAP_DESTINATION_MARK,
  type AmapCast,
  type AmapClient,
  type AmapClientOptions,
  type AmapForecast,
  type AmapPlace,
  type AmapPoi,
  type AmapPath,
  type AmapRegeo,
  type LngLat,
} from "./amap";
export {
  amapFamilyOf,
  amapKeyFingerprint,
  beijingDay,
  buildAmapPoolSnapshot,
  createMemoryAmapLedger,
  // Redis 台账（M100-02）：同步返回、懒连接、连不上退回进程内；装配层只管把 REDIS_URL 递进去。
  createRedisAmapLedger,
  parseAmapDailyBudget,
  sumByFamily,
  AMAP_API_FAMILIES,
  AMAP_OUTCOMES,
  AMAP_POOL_KEY_PREFIX,
  type AmapApiFamily,
  type AmapDailyBudget,
  type AmapOutcome,
  type AmapPoolKeyRef,
  type AmapPoolKeyStatus,
  type AmapPoolSnapshot,
  type AmapRedisLedger,
  type AmapRedisLike,
  type AmapResetObservation,
  type AmapRetiredInfo,
  type AmapUsageLedger,
  type AmapUsageSnapshot,
} from "./amap-ledger";
export {
  mapRouteTool,
  AMAP_STRATEGY,
  ROUTE_STRATEGIES,
  setRestStopCandidateRecorder,
  type MapRouteArgs,
  type MapRouteData,
  type PlaceInput,
  type ResolvedPlace,
  type RestStop,
  type RestStopCandidateRecorder,
  type RouteSamplePoint,
  type RouteStrategy,
  type RouteSummary,
} from "./map-route";
export { computeTripLeg, roadCondition, roadLabel, type TripLegInput } from "./trip-leg";
export {
  ragflowTool,
  setRagClient,
  getRagClient,
  type RagflowArgs,
  type RagflowData,
} from "./ragflow";
export {
  submitHotelsTool,
  submitTourDaysTool,
  submitTransitTool,
  // ACR-047：段列表契约、续航评估与意图理解的提交通道
  submitDrivePlanTool,
  submitRangeAssessmentTool,
  submitIntentTool,
  assertDriveLegs,
  // 「这一轮第几次提交」（M94-04）：轨迹概括读它，单测靠 reset 清场。
  submitAttempts,
  resetSubmitAttempts,
  submitNavPlanTool,
  submitGuideSpotsTool,
  submitGuideAccessTool,
  submitGuideComfortTool,
  setBranchSubmissionSink,
  type BranchSubmissionSink,
  type SubmissionRejection,
  type SubmitHotelsArgs,
  type SubmittedHotel,
  type SubmitGuideSpotsArgs,
  type SubmitGuideAccessArgs,
  type SubmitGuideComfortArgs,
  type SubmittedGuideSpot,
  type SubmitNavPlanArgs,
  type SubmittedNavWaypoint,
  type SubmitDrivePlanArgs,
  type DriveLeg,
  type DriveLegStop,
  type DriveStopKind,
  type DriveLegDirection,
  type SubmitRangeAssessmentArgs,
  type RangeBasis,
  type SubmitIntentArgs,
} from "./branch-submit";
export {
  webSearchTool,
  setWebSearch,
  getWebSearch,
  callAnthropicWebSearch,
  setSearchResultRecorder,
  type WebSearchConfig,
  type WebSearchArgs,
  type WebSearchData,
  type SearchResultRecorder,
  type CallWebSearchOptions,
} from "./web-search";
export {
  preferenceRecallTool,
  setPreferenceStore,
  getPreferenceStore,
  type PreferenceRecallArgs,
  type PreferenceRecallData,
  type PreferenceStore,
  type RecalledPreference,
} from "./memory";
export {
  energyGapTool,
  computeEnergyGap,
  setEnergyConsumptionLookup,
  lookupEnergyConsumption,
  type EnergyConsumptionLookup,
  type EnergyGapArgs,
  type EnergyGapData,
  type EnergyUnit,
} from "./energy-gap";
export {
  planAuditTool,
  auditPlan,
  hasBlocker,
  normalizePlace,
  type PlanAuditArgs,
  type PlanAuditLimits,
} from "./plan-audit";
export { cityDistrictsTool, type CityDistrictsArgs, type CityDistrict, type CityDistrictsResult } from "./city-districts";
export {
  itineraryAssembleTool,
  planEditTool,
  submitRepairsTool,
  submitVerdictTool,
  setReviewAssembler,
  getReviewAssembler,
  applyPlanEdits,
  PlanEditError,
  type ReviewAssembler,
  type ReviewCtx,
  type ReviewSnapshotView,
  type PlanEditOp,
  type PlanEditArgs,
  type RepairBranch,
  type SubmitRepairsArgs,
  type SubmitVerdictArgs,
  type VerdictRow,
} from "./trip-review-tools";
export {
  refuelLogTool,
  setRefuelStore,
  getRefuelStore,
  type RefuelLogArgs,
  type RefuelLogData,
  type RefuelLogStore,
  type RefuelRecordRow,
} from "./refuel-log";
export {
  dataFreshnessTool,
  setFreshnessThresholds,
  FRESHNESS_ITEM_LABEL,
  type DataFreshnessArgs,
  type DataFreshnessData,
} from "./data-freshness";
export {
  usageProfileTool,
  setUsageStore,
  getUsageStore,
  type UsageProfileArgs,
  type UsageProfileData,
} from "./usage-profile";
export {
  vehicleMemberTool,
  setMemberStores,
  getMemberStore,
  type VehicleMemberArgs,
  type VehicleMemberData,
  type MemberBrief,
  type MemberListData,
  type MemberProfileData,
  type MemberHistoryData,
} from "./vehicle-member";
// 联系方式读写（M19-06）。`resolveContactSecret` 也导出，但它**不是工具**——
// `test_drive_book` 用它在工具层内部取真号，见 contact.ts 末尾的说明。
export {
  contactLookupTool,
  contactUpdateTool,
  resolveContactSecret,
  type ContactLookupArgs,
  type ContactUpdateArgs,
  type ContactLookupData,
  type ContactUpdateData,
  type ContactBrief,
} from "./contact";
export {
  vehicleProfileTool,
  vehicleProfileWriteTool,
  setVehicleStore,
  getVehicleStore,
  type VehicleReadArgs,
  type VehicleReadData,
  type VehicleWriteArgs,
} from "./vehicle-profile";
export {
  chargingTool,
  createChargingTool,
  createAmapChargingBackend,
  planChargeStops,
  pointAlongRoute,
  parsePowerKw,
  haversineKm,
  SAFETY_SOC,
  TARGET_SOC,
  QUEUE_NOTICE,
  type ChargingArgs,
  type ChargingResult,
  type ChargingStop,
  type ChargingStation,
  type ChargingBackend,
} from "./charging";
export {
  setEnergyStopCandidateRecorder,
  setEnergyStopLookup,
  verifyEnergyStops,
  energyStopCore,
  MIN_CORE_CHARS,
  type EnergyStopCandidate,
  type EnergyStopCandidateRecorder,
  type EnergyStopKind,
  type EnergyStopLookup,
  type EnergyStopVerdict,
} from "./energy-stop-candidates";
export {
  chainsOf,
  samePlace,
  setRouteDurationLookup,
  setRouteDurationRecorder,
  toleranceFor,
  verifyLegMinutes,
  TOLERANCE_MIN,
  TOLERANCE_RATIO,
  type LegChain,
  type LegLike,
  type RouteDurationLookup,
  type RouteDurationRecord,
  type RouteDurationRecorder,
} from "./route-duration-ledger";
export {
  routeServicesTool,
  createRouteServicesTool,
  createAmapRouteServicesBackend,
  SERVICE_TYPECODES,
  SERVICE_RADIUS_M,
  NURSERY_ROOM_TYPECODE,
  MAX_PER_POINT,
  MAX_POINTS as ROUTE_SERVICES_MAX_POINTS,
  ROUTE_SERVICES_NOTICE,
  type ServiceCategory,
  type RouteServicesArgs,
  type RouteServicesResult,
  type RouteServicesBackend,
  type ServiceCategoryResult,
  type ServicePoi,
} from "./route-services";
export {
  poiSearchTool,
  spotSearchTool,
  hotelSearchTool,
  createPoiSearchTool,
  type PoiSearchToolOptions,
  PRICE_NOTICE,
  type PoiSearchArgs,
  type PoiSearchResult,
  type PoiCandidate,
  type PoiSearchBackend,
  type PoiCategory,
  setPoiCoordSink,
  type PoiCoordSink,
} from "./poi-search";
export {
  routeAuditTool,
  createRouteAuditTool,
  setRouteAuditStore,
  auditDay,
  auditJourney,
  optimizeOrder,
  findCrossings,
  pathKm,
  ROUTE_AUDIT_NOTICE,
  type RouteAuditArgs,
  type RouteAuditResult,
  type RouteAuditDayResult,
  type JourneyAudit,
  type JourneyDayInput,
  type JourneyRegroupSuggestion,
  type JourneyDayOrderSuggestion,
  type RouteAuditRecordPayload,
  type RouteAuditStore,
  type RouteGeocodeBackend,
  type RoutePoint,
} from "./route-audit";
export {
  transitRouteTool,
  createTransitRouteTool,
  TRANSIT_NOTE,
  type TransitRouteArgs,
  type TransitRouteResult,
  type TrainOption,
  type TransitBackend,
} from "./transit-route";
export {
  carCatalogTool,
  createCarCatalogTool,
  createRagCatalogBackend,
  type CarCatalogArgs,
  type CarCatalogResult,
  type CatalogChunk,
  type CatalogBackend,
  type RagRetrieveLike,
} from "./car-catalog";
export {
  tripPlanCommitTool,
  tripPlanCancelTool,
  tripPlanUpdateTool,
  tripPlanNavTool,
  tripPlanListTool,
  tripPlanQueryTool,
  setTripPlanStore,
  type TripPlanCommitArgs,
  type TripPlanCommitData,
  type TripPlanNavArgs,
  type TripPlanNavData,
  type TripPlanStore,
} from "./trip-plan-commit";
export {
  dealerStoresTool,
  dealerSlotsTool,
  dealerPricingTool,
  testDriveBookTool,
  setDealerBackend,
  getDealerBackend,
  createHttpDealerBackend,
  type DealerBackend,
  type DealerStore,
  type DealerSlot,
  type DealerTrim,
  type DealerBooking,
  type TestDriveContact,
  type TestDriveBookArgs,
} from "./dealer";
export {
  appointmentTool,
  createAppointmentTool,
  createMockAppointmentBackend,
  createDealerAppointmentBackend,
  createRepairAppointmentBackend,
  setAppointmentBackend,
  describeDisclosure,
  maskPhone,
  type AppointmentArgs,
  type AppointmentResult,
  type AppointmentContact,
  type AppointmentKind,
  type AppointmentBackend,
} from "./appointment";
export {
  repairHistoryTool,
  repairQuoteTool,
  repairStationsTool,
  repairSlotsTool,
  setRepairBackend,
  getRepairBackend,
  createHttpRepairBackend,
  type RepairBackend,
  type RepairHistoryRecord,
  type RepairStation,
  type RepairSlot,
  type RepairQuote,
  type RepairQuoteItem,
} from "./repair";
export {
  insurancePolicyTool,
  insurancePrecheckTool,
  setInsuranceBackend,
  getInsuranceBackend,
  createHttpInsuranceBackend,
  type InsuranceBackend,
  type InsurancePolicy,
  type PrecheckResult,
  type PrecheckBreakdownRow,
  type PremiumForecast,
} from "./insurance-claims";
// 售后理赔两工具（M96-02，ACR-041）：材料时限是代码内词条；净收益把赔付与涨价放进同一个回答。
export {
  claimChecklistTool,
  claimChecklistFor,
  ACCIDENT_TYPES,
  ACCIDENT_TYPE_LABELS,
  type AccidentType,
  type ClaimChecklist,
} from "./claim-checklist";
export {
  claimAdvisorTool,
  leaningOf,
  policyKeyOf,
  policyKeySentence,
  type ClaimAdvice,
  type ClaimAdvisorArgs,
  type ClaimLeaning,
  type LossSource,
  type PolicyKey,
} from "./claim-advisor";
// 视觉观察层（M71-02，ACR-024）：不是工具、不进任何 Agent 的 ACL——它是与 ASR 同位的输入转换。
export * from "./vision";
// 视频抽帧与分段转写（M80-01，ACR-027）：同上，输入转换，不进 ACL；调用方是网关。
export * from "./media";
